// <auto-generated />
using System;
using JsonDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JsonDemo.Models.Charger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Id_Subjekt")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Zustelladresse")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Chargers");
                });

            modelBuilder.Entity("JsonDemo.Models.Charger", b =>
                {
                    b.OwnsOne("JsonDemo.Models.SubjektDto", "Subjekt", b1 =>
                        {
                            b1.Property<Guid>("ChargerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Adresse")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Vorname")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ChargerId");

                            b1.ToTable("Chargers");

                            b1.ToJson("Subjekt");

                            b1.WithOwner()
                                .HasForeignKey("ChargerId");
                        });

                    b.OwnsOne("JsonDemo.Models.SubjektDto", "Zustell_Subjekt", b1 =>
                        {
                            b1.Property<Guid>("ChargerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Adresse")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Vorname")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ChargerId");

                            b1.ToTable("Chargers");

                            b1.ToJson("Zustell_Subjekt");

                            b1.WithOwner()
                                .HasForeignKey("ChargerId");
                        });

                    b.Navigation("Subjekt");

                    b.Navigation("Zustell_Subjekt");
                });
#pragma warning restore 612, 618
        }
    }
}
